set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_CROSSCOMPILING 1)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

# set path to c99 and c++ compilers
# macOS Intel
# set(CMAKE_C_COMPILER /usr/local/opt/gcc-arm-none-eabi/bin/arm-none-eabi-gcc)
# set(CMAKE_CXX_COMPILER /usr/local/opt/gcc-arm-none-eabi/bin/arm-none-eabi-g++)
# macOS M1
set(CMAKE_C_COMPILER /opt/homebrew/opt/gcc-arm-none-eabi-10-2020-q4-major/bin/arm-none-eabi-gcc)
set(CMAKE_CXX_COMPILER /opt/homebrew/opt/gcc-arm-none-eabi-10-2020-q4-major/bin/arm-none-eabi-g++)

# suppress compiler checks
set(CMAKE_C_COMPILER_WORKS 1 CACHE INTERNAL "")
set(CMAKE_CXX_COMPILER_WORKS 1 CACHE INTERNAL "")

# set build flags
# set(FLAGS "-Os -fcheck-new -ffunction-sections -fdata-sections -fno-exceptions -fsigned-char -mcpu=cortex-m7 -mfpu=fpv5-d16 -mfloat-abi=hard -DARM_MATH_CM7 -u_printf_float -falign-functions=16 -fno-builtin-printf -fno-builtin-fprintf -fno-builtin-vprintf -fno-builtin-puts -mno-thumb-interwork -mthumb -MMD" CACHE STRING "" FORCE)
set(FLAGS "-Os -ffunction-sections -fdata-sections -fno-exceptions -mcpu=cortex-m7 -mfpu=fpv5-d16 -mfloat-abi=hard -DARM_MATH_CM7 -u_printf_float" CACHE STRING "" FORCE)

set(CMAKE_C_FLAGS_INIT "-std=gnu11 -Wno-unused-function -Wno-return-type -Wno-builtin-declaration-mismatch -Wno-implicit-function-declaration -Wno-unused-parameter -Wno-char-subscripts ${FLAGS} -DCLOCK_MONOTONIC=0 -D'__attribute__(x)='" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_INIT "-std=gnu++11 -Wno-unused-function -Wno-return-type -Wno-builtin-declaration-mismatch -Wno-implicit-function-declaration -Wno-unused-parameter -Wno-char-subscripts -fno-rtti ${FLAGS} -DCLOCK_MONOTONIC=0 -D'__attribute__(x)='" CACHE STRING "" FORCE)


# From ./waf build
# OPTIMIZE -Os
# MCU Flags: cortex-m7 ['-mcpu=cortex-m7', '-mfpu=fpv5-d16', '-mfloat-abi=hard']
# CPU_FLAGS=['-mcpu=cortex-m7', '-mfpu=fpv5-d16', '-mfloat-abi=hard', '-DARM_MATH_CM7', '-u_printf_float']
# CORTEX=cortex-m7
# CHIBIOS_BUILD_FLAGS=USE_FATFS=yes USE_LWIP=no CHIBIOS_STARTUP_MK=os/common/startup/ARMCMx/compilers/GCC/mk/startup_stm32h7xx.mk CHIBIOS_PLATFORM_MK=os/hal/ports/STM32/STM32H7xx/platform.mk MCU=cortex-m7 ENV_UDEFS=-DCHPRINTF_USE_FLOAT=1

# Checking for NEED_CMATH_ISNAN_STD_NAMESPACE: 13:29:34 runner [
# '/usr/local/opt/gcc-arm-none-eabi/bin/arm-none-eabi-g++',
# '-Werror=implicit-fallthrough',
# '-fcheck-new',
# '-fsingle-precision-constant',
# '-std=gnu++11',
# '-fdata-sections',
# '-ffunction-sections',
# '-fno-exceptions',
# '-fsigned-char',
# '-Wall',
# '-Wextra',
# '-Wpointer-arith',
# '-Wno-unused-parameter',
# '-Wno-missing-field-initializers',
# '-Wno-reorder',
# '-Wno-redundant-decls',
# '-Wno-unknown-pragmas',
# '-Wno-expansion-to-defined',
# '-Werror=cast-align',
# '-Werror=attributes',
# '-Werror=format-security',
# '-Werror=format-extra-args',
# '-Werror=enum-compare',
# '-Werror=format',
# '-Werror=array-bounds',
# '-Werror=uninitialized',
# '-Werror=init-self',
# '-Werror=narrowing',
# '-Werror=return-type',
# '-Werror=switch',
# '-Werror=sign-compare',
# '-Werror=type-limits',
# '-Werror=undef',
# '-Werror=unused-result',
# '-Werror=shadow',
# '-Werror=unused-value',
# '-Werror=unused-variable',
# '-Werror=delete-non-virtual-dtor',
# '-Wfatal-errors',
# '-Wno-trigraphs',
# '-Werror=parentheses',
# '-DARDUPILOT_BUILD',
# '-Wuninitialized',
# '-Warray-bounds',
# '-Wno-format-contains-nul',
# '-Werror=unused-but-set-variable',
# '-Werror=suggest-override',
# '-Werror=implicit-fallthrough',
# '-Werror=maybe-uninitialized',
# '-Werror=duplicated-cond',
# '-Werror=sizeof-pointer-div',
# '-g',
# '-O0',
# '-D__AP_LINE__=__LINE__',
# '-ffunction-sections',
# '-fdata-sections',
# '-fsigned-char',
# '-Wall',
# '-Wextra',
# '-Werror=format',
# '-Wpointer-arith',
# '-Wcast-align',
# '-Wno-missing-field-initializers',
# '-Wno-unused-parameter',
# '-Wno-redundant-decls',
# '-Wno-unknown-pragmas',
# '-Wno-trigraphs',
# '-Werror=shadow',
# '-Werror=return-type',
# '-Werror=unused-result',
# '-Werror=unused-variable',
# '-Werror=narrowing',
# '-Werror=attributes',
# '-Werror=overflow',
# '-Werror=parentheses',
# '-Werror=format-extra-args',
# '-Werror=ignored-qualifiers',
# '-Werror=undef',
# '-DARDUPILOT_BUILD',
# '-Wno-format-contains-nul', '-fsingle-precision-constant',
# '-g',
# '-O0',
# '-mcpu=cortex-m7',
# '-mfpu=fpv5-d16',
# '-mfloat-abi=hard',
# '-DARM_MATH_CM7',
# '-u_printf_float',
# '-Wlogical-op',
# '-Wframe-larger-than=1300',
# '-Wno-attributes',
# '-fno-exceptions',
# '-Wall', '-Wextra',
# '-Wno-sign-compare',
# '-Wfloat-equal',
# '-Wpointer-arith',
# '-Wmissing-declarations',
# '-Wno-unused-parameter',
# '-Werror=array-bounds',
# '-Wfatal-errors',
# '-Werror=uninitialized',
# '-Werror=init-self',
# '-Werror=unused-but-set-variable',
# '-Wno-missing-field-initializers',
# '-Wno-trigraphs',
# '-fno-strict-aliasing',
# '-fomit-frame-pointer',
# '-falign-functions=16',
# '-ffunction-sections',
# '-fdata-sections',
# '-fno-strength-reduce',
# '-fno-builtin-printf',
# '-fno-builtin-fprintf',
# '-fno-builtin-vprintf',
# '-fno-builtin-vfprintf',
# '-fno-builtin-puts',
# '-mno-thumb-interwork',
# '-mthumb',
# '--specs=nano.specs',
# '--specs=nosys.specs',
# '-D__USE_CMSIS',
# '-Werror=deprecated-declarations',
# '-DNDEBUG=1',
# '-Wno-error=double-promotion',
# '-Wno-error=missing-declarations',
# '-Wno-error=float-equal',
# '-Wno-error=cpp',
# '-fno-rtti',
# '-fno-threadsafe-statics',
# '-Werror',
# '-MMD',
# '-Og',
# '-I../../../../libraries/AP_GyroFFT/CMSIS_5/include',
# '-I../../../../modules/DroneCAN/libcanard',
# '-DAP_CUSTOMCONTROL_ENABLED=0',
# '-DAP_DDS_ENABLED=0',
# '-DAP_SCRIPTING_CHECKS=1',
# '-DAP_SCRIPTING_ENABLED=0',
# '-DAP_SIM_ENABLED=0',
# '-DAP_UROS_ENABLED=1',
# '-DCANARD_ENABLE_CANFD=1',
# '-DCANARD_IFACE_ALL=1',
# '-DCONFIG_HAL_BOARD=HAL_BOARD_CHIBIOS',
# '-DENABLE_HEAP=1',
# '-DENABLE_ONVIF=0',
# '-DHAL_DEBUG_BUILD=1',
# '-DHAVE_STD_NULLPTR_T=0',
# '-DLUA_32BITS=1',
# '-DUSE_LIBC_REALLOC=0',
# '-DWAF_BUILD=1',

# '-DPYTHONDIR="/usr/lib/python3.11/site-packages"',
# '-DPYTHONARCHDIR="/usr/lib/python3.11/site-packages"',
# '-D__STDC_FORMAT_MACROS=1',
# '-DDRONECAN_CXX_WRAPPERS=1',
# '-DUSE_USER_HELPERS=1',
# '-DCANARD_ENABLE_DEADLINE=1',
# '-DCANARD_MULTI_IFACE=1',
# '-DCANARD_ALLOCATE_SEM=1',
# '-DUAVCAN_SUPPORT_CANFD=1',
# '-DAP_SIGNED_FIRMWARE=0',
# '-DHAVE_CMATH_ISFINITE=1',
# '-DHAVE_CMATH_ISINF=1',
# '-DHAVE_CMATH_ISNAN=1',
# '-DNEED_CMATH_ISFINITE_STD_NAMESPACE=1',
# '-DNEED_CMATH_ISINF_STD_NAMESPACE=1',
# '../../test.cpp',
# '-c',
# '-otest.cpp.1.o']

# 13:29:34 runner ['/usr/local/opt/gcc-arm-none-eabi/bin/arm-none-eabi-g++',
# '-mcpu=cortex-m7',
# '-mfpu=fpv5-d16',
# '-mfloat-abi=hard',
# '-DARM_MATH_CM7',
# '-u_printf_float',
# '-fomit-frame-pointer',
# '-falign-functions=16',
# '-ffunction-sections',
# '-fdata-sections',
# '-u_port_lock',
# '-u_port_unlock',
# '-u_exit',
# '-u_kill',
# '-u_getpid',
# '-u_errno',
# '-uchThdExit',
# '-fno-common',
# '-nostartfiles',
# '-mno-thumb-interwork',
# '-mthumb',
# '--specs=nano.specs',
# '--specs=nosys.specs',
# '-L/Volumes/MacPro2_DV1/Code/ardupilot/ardupilot/build/MatekH743',
# '-L/Volumes/MacPro2_DV1/Code/ardupilot/ardupilot/modules/ChibiOS/os/common/startup/ARMCMx/compilers/GCC/ld',
# '-L/Volumes/MacPro2_DV1/Code/ardupilot/ardupilot/libraries/AP_HAL_ChibiOS/hwdef/common',
# '-Wl,-Map,Linker.map,--cref,--gc-sections,--no-warn-mismatch,--library-path=/ld,--script=ldscript.ld,--defsym=__process_stack_size__=0x1C00,--defsym=__main_stack_size__=0x600',
# '-gdwarf-4',
# '-g3',
# 'test.cpp.1.o',
# '-otestprog',
# '-lgcc',
# '-lm']
# yes 